spring:
  profiles:
    active: dev
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314
wx:
  miniapp:
    configs:
        - appid: wx54f2bccf846435c6
          secret: 83a3244d55199f7f528ac5a2c363255c
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON