spring:
  profiles:
    active: dev
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314
wx:
  miniapp:
    configs:
        - appid: wxf11c2dc12fc5585b
          secret: 057e0ce2c305f25950862ff1c400ca3e
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON